FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./frontend/package*.json ./frontend/
COPY ./shared/package*.json ./shared/

RUN npm ci -w frontend

COPY ./frontend/ ./frontend/
COPY ./shared/ ./shared/

ARG APP_TODO_API
ENV REACT_APP_TODO_API ${APP_TODO_API}
RUN npm run build -w frontend

EXPOSE 3000

CMD ["npx", "serve", "frontend/build"]