version: "3.8"
services:
  backend:
    build:
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URL=mongodb://db:27017/mytodos
      - POSTGRES_URL=postgres://todoapp:todoapp@localhost:5432/todoapp

  frontend:
    build:
      dockerfile: Dockerfile.frontend
      args:
        APP_TODO_API: http://localhost:4000
    ports:
      - "3000:3000"

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    container_name: db
    volumes:
      - /data/db
      - ./sql/initdb.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_USER=todoapp
      - POSTGRES_PASSWORD=todoapp
      - POSTGRES_DB=todoapp
      - PGDATA=/data/db
